apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - configuration.yaml
resources:
  - app.yaml
configMapGenerator:
  - name: demo-app
    literals:
      - "MANAGEMENT_OTLP_TRACING_ENDPOINT=http://tempo.tempo:4318/v1/traces"
